---
name: CMake_tests
on:
  push:
    branches:
      - CI
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: build-essential cmake wget git gawk libzstd-dev libjsoncpp-dev pkg-config

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_OTF2=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: set htf_print_path
        run:
          echo "HTF_PRINT_PATH=${{github.workspace}}/build/apps/htf_print" >> $GITHUB_ENV

      - name: set htf_info_path
        run:
          echo "HTF_INFO_PATH=${{github.workspace}}/build/apps/htf_info" >> $GITHUB_ENV

      - name: Unit Test
        working-directory: ${{github.workspace}}/build
        run: |
          echo "htf_print_path: ${{env.HTF_PRINT_PATH}}
          ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
