---
name: CMake_tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
	
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
	with:
	   packages: build-essential cmake wget git gawk libzstd-dev libjsoncpp-dev pkg-config libzfp-dev
      # - name: download-openmpi
      #   run: wget
      #     https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.5.tar.gz
      # - name: extract-openmpi
      #   run: tar -xvf ./openmpi-4.1.5.tar.gz
      # - name: configure-openmpi
      #   run: ./openmpi-4.1.5/configure --prefix="/home/${USER}/.openmpi"
      # - name: install-openmpi
      #   run: |
      #     make -j
      #     sudo make install
      # - name: set-openmpi-path
      #   run: |
      #     export PATH=${PATH}:/home/${USER}/.openmpi/bin/
      #     export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/${USER}/.openmpi/lib/
      #     echo ${PATH}
      #     echo ${LD_LIBRARY_PATH}
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_OTF2=ON -DENABLE_ZFP=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
