---
name: Validation_tests
on:
  workflow_dispatch:
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  build:
    runs-on: ubuntu-latest
    container: ftrahay/htf:test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure HTF
        run: cmake  -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/htf/install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_OTF2=ON -DENABLE_ZFP=ON -DENABLE_SZ=ON
      - name: Build HTF
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Install HTF
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: export HTF
        run: echo "${{github.workspace}}/htf/install/bin" >> $GITHUB_PATH

      - name: Unit Test
        run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build

      - name: Checkout eztrace
        shell: bash
        run: git clone --depth=1 --single-branch https://gitlab.com/eztrace/eztrace.git ${{github.workspace}}/eztrace
      - name: Configure EZTrace
        run: cmake ${{github.workspace}}/eztrace -B ${{github.workspace}}/eztrace/build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/eztrace/install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEZTRACE_ENABLE_PTHREAD=ON
      - name: Build EZTrace
        run: cmake --build ${{github.workspace}}/eztrace/build --config ${{env.BUILD_TYPE}}
      - name: Install EZTrace
        run: cmake --install ${{github.workspace}}/eztrace/build --config ${{env.BUILD_TYPE}}
        run: echo "${{github.workspace}}/eztrace/install/bin" >> $GITHUB_PATH

      - name: Test EZTrace:pthread
        run: |
	  cd  ${{github.workspace}}/eztrace/test/pthread
	  make
	  bash ./test_dummy.sh
